# Generated by Django 4.2.1 on 2023-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="part_id",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
