# Generated by Django 4.2.1 on 2023-06-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_part_part_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="revision",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
