# Generated by Django 4.2.1 on 2023-06-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_id",
                    models.CharField(
                        blank=True, editable=False, max_length=6, null=True, unique=True
                    ),
                ),
                ("description", models.CharField(max_length=512)),
                ("customer_part", models.CharField(max_length=128)),
                ("revision", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_customer",
                        to="Customers.customer",
                    ),
                ),
            ],
        ),
    ]
