# Generated by Django 4.2.1 on 2023-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boost_id",
                    models.CharField(
                        blank=True, editable=False, max_length=5, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
    ]
